feat: added events page
dscatc/dscatc.github.io pull request #4
Opened 2019-09-21 18:43 UTC by indraasura

Created page for events

2019-09-21 20:00 UTC, shashank-sharma requested changes
Before merging it and showing it in production site, please change :)

2019-09-21 20:00 UTC, shashank-sharma commented on events.html
> +    <title>DSC ATC | Team Members</title>
Change Title

2019-09-21 20:00 UTC, shashank-sharma commented on events.html
> +    <link rel="stylesheet" type="text/css" href="css/tilter.css">
tilter.css not required including anime.js

2019-09-21 20:00 UTC, shashank-sharma commented on events.html
> +    <script src="js/tilter.js"></script>
Not required

2019-09-21 20:00 UTC, shashank-sharma commented on events.html
> +        <div class = "col s12 m4 l4">
Can you remove duplicate cards, or add coming soon card with workable button

2019-09-21 20:00 UTC, shashank-sharma commented on index.html
> +<!-- <div class="bouncing-loader" id="preloader">
Remove comment for loader

2019-09-22 14:45 UTC, indraasura commented on events.html
> +    <title>DSC ATC | Team Members</title>
Cool, done!

2019-09-22 14:45 UTC, indraasura commented on events.html
> +        <div class = "col s12 m4 l4">
okay, will do it

2019-09-23 04:51 UTC, indraasura commented on events.html
> +    <link rel="stylesheet" type="text/css" href="css/tilter.css">
done

2019-09-23 05:08 UTC, closed without merging